import type { CharacterDefinition } from "../types";

export const characters: Record<string, CharacterDefinition> = {
  xie: {
    id: "xie-mingwei",
    name: "谢明微",
    rank: "尚仪局司籍女史",
    zodiac: "snake",
    archetype: "镜中复核者",
    publicPersona: "不先断真假，只问这一页是谁、何时、经谁递来的。",
    hiddenMotivation: "让任何新秩序都无法绕开她写下的复核规则。",
    portrait: "/characters/xie-mingwei-registrar-v01.webp",
    focalPoint: { x: 48, y: 13 },
    expressions: {},
    zodiacIcon: "巳",
    abilities: ["版本复核", "异议附卷", "流程预判"],
  },
  dowager: {
    id: "cui-empress-dowager",
    name: "崔氏",
    rank: "皇太后",
    zodiac: "ox",
    archetype: "守制见证者",
    publicPersona: "言辞简短，只问天亮以后由谁承担。",
    hiddenMotivation: "让权力更替仍有人承认，同时避免王朝沦为母族私产。",
    portrait: "/characters/cui-empress-dowager-v01.webp",
    focalPoint: { x: 50, y: 13 },
    expressions: {},
    zodiacIcon: "丑",
    abilities: ["礼制见证", "名分质询", "体面交接"],
  },
  queen: {
    id: "shen-lingyi",
    name: "沈令仪",
    rank: "皇后",
    zodiac: "rabbit",
    archetype: "静观执局者",
    publicPersona: "端庄、公正、从不提高声音。",
    hiddenMotivation: "维持宫闱稳定，厌恶无谓风波。",
    portrait: "/characters/shen-lingyi-rabbit-formal-v01.webp",
    focalPoint: { x: 50, y: 17 },
    expressions: {},
    zodiacIcon: "卯",
    abilities: ["静观", "关系洞察", "秩序维护"],
  },
  zhaoyi: {
    id: "gu-minghua",
    name: "顾明华",
    rank: "昭仪",
    zodiac: "tiger",
    archetype: "天然执事者",
    publicPersona: "才名远播，慷慨得体。",
    hiddenMotivation: "希望主掌下一件宫中大事。",
    portrait: "/characters/gu-minghua-tiger-formal-v01.webp",
    focalPoint: { x: 49, y: 16 },
    expressions: {},
    zodiacIcon: "寅",
    abilities: ["直取", "主事", "御前声势"],
  },
  eunuch: {
    id: "gao-fuan",
    name: "高福安",
    rank: "内侍",
    zodiac: "rat",
    archetype: "消息经纪人",
    publicPersona: "客气、眼明、总在近旁。",
    hiddenMotivation: "以人情交换消息，记得谁把他当作透明人。",
    portrait: "/characters/gao-fuan-rat-formal-v01.webp",
    focalPoint: { x: 51, y: 17 },
    expressions: {},
    zodiacIcon: "子",
    abilities: ["听风", "记事", "消息交换"],
  },
};
